### ISSUE TITLE
okvtwo通过 CloudFlare Workers 反向代理！！这个怎样搞？？

### ISSUE THREAD

**Issue by kitkw** [yunbaitech666/okvtwo#2]
我按照HerokuXray项目的方法搞，搞不成...........................

大佬请指点！！先谢过！！

**Comment by yunbaitech666** [comment]
https://youtu.be/RzeGi1CPWKk

**Comment by kitkw** [comment]
> https://youtu.be/RzeGi1CPWKk

SORRY！！ 原来自己搞成功了只不过XXX.cloud.okteto.net的页面是Bad Request
（跟XXX.herokuapp.com不一样，还以为失败了），CloudFlare Workers下也见不到请求量的。
其实可以正常使用的。
那个免费的对我不起作用。okvtwo直连或中转都是0.多M/S。
现在挂CF直接8+M/S
感谢回复！！

**Comment by yunbaitech666** [comment]
订阅一下我的频道

**Comment by kitkw** [comment]
> 订阅一下我的频道

有在订阅呢！！支持继续分享免费搭建的VPS。那些大厂云申请真它妈麻烦............

**Comment by kitkw** [comment]
> 订阅一下我的频道

大佬一个github帐号能不能部署多个VPS？？
okteto现在是用gitlab.com
Heroku现在是用github.com
现在想搞个火车头用同个github号会不会冲突？？
还有这些 VPS 的  时限 / 限流  各是多少？视频好像都没怎样提到，只知道Heroku是550小时

**Comment by kitkw** [comment]
还有HAX

**Comment by yunbaitech666** [comment]
hax一周续期一次，可以长期使用。okteto可以长期使用，直到封号。一个github帐号可以部署多个，但是 有封号风险，别用常用的

**Comment by kitkw** [comment]
![Screenshot 2021-11-28 140033](https://user-images.githubusercontent.com/31963066/143731703-f790b432-085d-4732-aa7d-437b90d74d74.png)
我就是YT上提问《DNS 那步我只有IPV4!!也选择不了AAAA...........》
Sorry!! 暂时用不了TG，因为GV号收不了TG的验证码，暂时没有帐号。VPS也是用朋友的号申请的。

就是  类型  选择那里是 灰键的   选择不了AAAA类型........................

**Comment by kitkw** [comment]
> hax一周续期一次，可以长期使用。okteto可以长期使用，直到封号。一个github帐号可以部署多个，但是 有封号风险，别用常用的

火车头呢？这个真延迟最低的

**Comment by yunbaitech666** [comment]
![图片](https://user-images.githubusercontent.com/89902918/143731864-dc2bab07-760c-415e-9e5b-e53544aae32d.png)
这个地方选择AAAA，

火车头和okteto一样，也是容易封号，不知道哪天就不能用了。

**Comment by kitkw** [comment]
> ![图片](https://user-images.githubusercontent.com/89902918/143731864-dc2bab07-760c-415e-9e5b-e53544aae32d.png) 这个地方选择AAAA，
> 
> 火车头和okteto一样，也是容易封号，不知道哪天就不能用了。

选择不了啊    点不开的。   灰键

**Comment by yunbaitech666** [comment]
你看视频了吗？你肯定前边操作有问题，就添加个dns而已

**Comment by yunbaitech666** [comment]
真头一回碰到问这种问题的,你添加一个记录,类型选AAAA。没啥技术含量，你是小白吗？

**Comment by kitkw** [comment]
> 真头一回碰到问这种问题的,你添加一个记录,类型选AAAA。没啥技术含量，你是小白吗？

是真小白！！不过现在可以了。浏览器正常模式下  这个类型是选择不了的  点不了的  所以见不了下拉选项。

不过刚刚打开 浏览器匿名模式  下操作   就可以选择到......................
这也是醉了............

**Comment by yunbaitech666** [comment]
进电报群学习一下。  https://t.me/yunbaitech_chat

**Comment by kitkw** [comment]
> 进电报群学习一下。 https://t.me/yunbaitech_chat

好！先教我一下怎样用GV号注册TG，也试过用手机APP注册 但就是收不到验证码。网上有说可能是梯子太公车，但我用的都是这几个VPS搭建的

**Comment by yunbaitech666** [comment]
国内手机号就可以

**Comment by kitkw** [comment]
> 国内手机号就可以

不想用....

**Comment by kitkw** [comment]
> 国内手机号就可以

0000000000

**Comment by kitkw** [comment]
> 进电报群学习一下。 https://t.me/yunbaitech_chat

重启了下VPS终于可以正常运行命令安装。
但都域名输入又卡关..........
重试几次还是这样
域名:mini.bubululu.tk
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
nginx: [emerg] still could not bind()
 ---> Nginx启动失败 
 ---> 请手动尝试安装nginx后，再次执行脚本

**Comment by kitkw** [comment]
![vvvv](https://user-images.githubusercontent.com/31963066/143752146-fb86c24a-d4c4-4a45-b0ed-b300fbe1a5af.png)

**Comment by yunbaitech666** [comment]
如果失败了，先重装系统

**Comment by kitkw** [comment]
> 如果失败了，先重装系统

可以了！！还是第一次遇到要不断重启VPS的情况

**Comment by kitkw** [comment]
> > 如果失败了，先重装系统
> 
> 可以了！！还是第一次遇到要不断重启VPS的情况

搭建成功，但线路不通   小云朵开了   伪装路径也改了  优先IP也加了

**Comment by yunbaitech666** [comment]
进电报群。 https://t.me/yunbaitech_chat ， 管理员会给你解答，别在这发了
